[build]
  publish = "/"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom domain configuration
[context.production]
  environment = { NETLIFY_SITE_NAME = "jmefitlanding" }

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
